configfile: "config/config.yaml"

VARIABLES = {v["name"]: v["type"] for v in config["variables"]}


rule all:
    input:
        "data/processed/metabolomics_tvas.csv",
        "data/processed/clinical_tvas.csv",
        "data/processed/clinical_guide.csv",
        "data/processed/transcriptomics_tvas.csv",
        expand("results/metabolomics/limma/{variable}/done.txt",
               variable=VARIABLES.keys()),
        expand("results/proteomics/limma/{variable}/done.txt",
               variable=VARIABLES.keys()),
        "results/clinics/descriptive/continuous.csv",
        "results/clinics/descriptive/categorical.csv",
        "results/clinics/descriptive_stratified/descriptive_table_stratified.csv",
        "results/metabolomics/summary_heatmap.png",
        "results/proteomics/summary_heatmap.png",
        "results/report/atheromics_tvas_report.pptx"


rule preprocess_metabolomics:
    input:
        "data/raw/metabolomics/log_transformed_data.csv"
    output:
        "data/processed/metabolomics_tvas.csv"
    script:
        "scripts/preprocess_metabolomics.py"


rule preprocess_clinical:
    input:
        "data/raw/metabolon e glicemia 090926_rev_LA.xlsx",
        "data/processed/metabolomics_tvas.csv"
    output:
        "data/processed/clinical_tvas.csv",
        "data/processed/clinical_guide.csv"
    script:
        "scripts/preprocess_clinical.py"


rule preprocess_proteomics:
    input:
        "data/raw/proteomics/FedericiAllPlates_Extended_NPX_2026-03-11.csv",
        "data/processed/metabolomics_tvas.csv"
    output:
        "data/processed/proteomics_all.csv",
        "data/processed/proteomics_tvas.csv"
    script:
        "scripts/preprocess_proteomics.py"


rule preprocess_transcriptomics:
    input:
        "data/raw/transcriptomics/featureCounts_napoli_harmonized_qcfilt.tsv",
        "data/processed/metabolomics_tvas.csv"
    output:
        "data/processed/transcriptomics_tvas.csv"
    script:
        "scripts/preprocess_transcriptomics.py"


rule descriptive_clinical:
    input:
        clinical = "data/processed/clinical_tvas.csv",
        guide    = "data/processed/clinical_guide.csv"
    output:
        "results/clinics/descriptive/continuous.csv",
        "results/clinics/descriptive/categorical.csv"
    script:
        "scripts/descriptive_clinical.py"


rule descriptive_clinical_stratified:
    input:
        clinical = "data/processed/clinical_tvas.csv",
        guide    = "data/processed/clinical_guide.csv"
    output:
        "results/clinics/descriptive_stratified/descriptive_table_stratified.csv"
    params:
        strat_var    = config["stratified_descriptive"]["strat_var"],
        group_labels = config["stratified_descriptive"]["group_labels"],
        exclude      = config["stratified_descriptive"]["exclude"],
        out_dir      = "results/clinics/descriptive_stratified/",
        script       = "workflow/scripts/clinical_descriptive_stratified.py"
    shell:
        """
        python {params.script} \
            --input        {input.clinical} \
            --guide        {input.guide} \
            --strat_var    {params.strat_var} \
            --group_labels "{params.group_labels}" \
            --exclude      {params.exclude} \
            --out_dir      {params.out_dir}
        """


rule summary_heatmap:
    input:
        expand("results/{omic}/limma/{variable}/done.txt",
               variable=VARIABLES.keys(), allow_missing=True)
    output:
        "results/{omic}/summary_heatmap.png"
    params:
        results_dir = "results/{omic}/limma/",
        script      = "workflow/scripts/summary_heatmap.py"
    shell:
        """
        python {params.script} \
            --omic    {wildcards.omic} \
            --results {params.results_dir} \
            --out     {output}
        """


rule report_pptx:
    input:
        continuous  = "results/clinics/descriptive/continuous.csv",
        categorical = "results/clinics/descriptive/categorical.csv",
        stratified  = "results/clinics/descriptive_stratified/descriptive_table_stratified.csv",
        heatmap_met = "results/metabolomics/summary_heatmap.png",
        heatmap_pro = "results/proteomics/summary_heatmap.png"
    output:
        "results/report/atheromics_tvas_report.pptx"
    script:
        "scripts/make_pptx_report.py"


rule limma_proteomics:
    input:
        data  = "data/processed/proteomics_tvas.csv",
        meta  = "data/processed/clinical_tvas.csv",
        guide = "data/processed/clinical_guide.csv"
    output:
        "results/proteomics/limma/{variable}/done.txt"
    params:
        var_type   = lambda wc: VARIABLES[wc.variable],
        covariates = config["covariates"],
        out_dir    = "results/proteomics/limma/{variable}/",
        script     = "workflow/scripts/proteomics_limma.R"
    shell:
        """
        Rscript {params.script} \
            --variable   {wildcards.variable} \
            --type       {params.var_type} \
            --covariates {params.covariates} \
            --input      {input.data} \
            --metadata   {input.meta} \
            --guide      {input.guide} \
            --out_dir    {params.out_dir} \
        && touch {output}
        """


rule limma_metabolomics:
    input:
        data  = "data/processed/metabolomics_tvas.csv",
        meta  = "data/processed/clinical_tvas.csv",
        guide = "data/processed/clinical_guide.csv"
    output:
        "results/metabolomics/limma/{variable}/done.txt"
    params:
        var_type   = lambda wc: VARIABLES[wc.variable],
        covariates = config["covariates"],
        out_dir    = "results/metabolomics/limma/{variable}/",
        script     = "workflow/scripts/metabolomics_limma.R"
    shell:
        """
        Rscript {params.script} \
            --variable   {wildcards.variable} \
            --type       {params.var_type} \
            --covariates {params.covariates} \
            --input      {input.data} \
            --metadata   {input.meta} \
            --guide      {input.guide} \
            --out_dir    {params.out_dir} \
        && touch {output}
        """
